name: Feature Request
description: Suggest an idea or feature enhancement for the application
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what feature or enhancement you would like to see.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Context
      description: Why would this feature be useful?
    validations:
      required: false
